[package]
name = "typf-fontdb"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
typf-core = { workspace = true }
read-fonts = { workspace = true }
skrifa = { workspace = true }
thiserror = { workspace = true }
log = { workspace = true }