[package]
name = "typf-shape-none"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
typf-core = { workspace = true }
log = { workspace = true }